-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color14 = '#71717A'
local Color5 = '#FFEF8A'
local Color9 = '#18181B'
local Color13 = '#52525B'
local Color2 = '#A3E635'
local Color0 = '#F87171'
local Color1 = '#C3B6FD'
local Color8 = '#3F3F46'
local Color10 = '#27272A'
local Color11 = '#354320'
local Color7 = '#FAFAFA'
local Color15 = '#979798'
local Color6 = '#D4D4D8'
local Color4 = '#F59E0C'
local Color12 = '#5e3335'
local Color3 = '#E4E4E7'

highlight('Identifier', nil, Color0, nil)
highlight('Keyword', nil, Color1, nil)
highlight('Conditional', nil, Color1, nil)
highlight('Type', nil, Color1, nil)
highlight('Repeat', nil, Color1, nil)
highlight('Constant', nil, Color2, nil)
highlight('String', nil, Color2, nil)
highlight('Number', nil, Color2, nil)
highlight('Operator', nil, Color3, nil)
highlight('Type', nil, Color4, nil)
highlight('Function', nil, Color5, nil)
highlight('Function', nil, Color5, nil)
highlight('Comment', nil, Color6, nil)
highlight('StatusLine', Color7, Color8, nil)
highlight('WildMenu', Color9, Color7, nil)
highlight('Pmenu', Color9, Color7, nil)
highlight('PmenuSel', Color7, Color10, nil)
highlight('PmenuThumb', Color9, Color7, nil)
highlight('DiffAdd', Color11, nil, nil)
highlight('DiffDelete', Color12, nil, nil)
highlight('Normal', Color9, Color7, nil)
highlight('Visual', Color13, nil, nil)
highlight('CursorLine', Color13, nil, nil)
highlight('ColorColumn', Color13, nil, nil)
highlight('SignColumn', Color9, nil, nil)
highlight('LineNr', nil, Color14, nil)
highlight('TabLine', Color9, Color15, nil)
highlight('TabLineSel', Color7, Color10, nil)
highlight('TabLineFill', Color9, Color15, nil)
highlight('TSPunctDelimiter', nil, Color7, nil)

link('TSComment', 'Comment')
link('TSRepeat', 'Repeat')
link('TSField', 'Constant')
link('TSString', 'String')
link('TSFuncMacro', 'Macro')
link('TSConstant', 'Constant')
link('TSProperty', 'TSField')
link('TSTagDelimiter', 'Type')
link('TSFloat', 'Number')
link('Folded', 'Comment')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('Operator', 'Keyword')
link('TSNumber', 'Number')
link('Conditional', 'Operator')
link('TSOperator', 'Operator')
link('TSParameterReference', 'TSParameter')
link('CursorLineNr', 'Identifier')
link('TSLabel', 'Type')
link('TSKeyword', 'Keyword')
link('TSTag', 'MyTag')
link('TSConditional', 'Conditional')
link('TSType', 'Type')
link('Macro', 'Function')
link('NonText', 'Comment')
link('Whitespace', 'Comment')
link('TSPunctBracket', 'MyTag')
link('TelescopeNormal', 'Normal')
link('TSFunction', 'Function')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('TSParameter', 'Constant')
link('Repeat', 'Conditional')
link('TSNamespace', 'TSType')
