wallpaper {
	monitor = HDMI-A-1
	path = /home/aldenluthfi/susunluthfi/agnostic/wallpapers/Lenstra.png
}

wallpaper {
	monitor = HDMI-A-2
	path = /home/aldenluthfi/susunluthfi/agnostic/wallpapers/Lenstra.png
}

splash = false
